### ISSUE TITLE
状況 features が追加可能かどうかを検証する

### ISSUE THREAD

**Issue by ghost** [taisei-watanabe/recbole-playground#1]
## 背景

RecBole の環境下において、user 特徴量や item 特徴量の他に interaction 毎に変化する状況を表現した特徴量を取り入れたい。

## 課題

RecBole の環境下において、user 特徴量や item 特徴量の他に interaction 毎に変化する状況を表現した特徴量を取り入れる方法が判明していない。

## 目的

RecBole の環境下において、user 特徴量や item 特徴量の他に interaction 毎に変化する状況を表現した特徴量を取り入れる方法を明らかにすること。
明らかになった場合には、それを README.md に記載すること。

**Comment by ghost** [comment]
## .inter に状況 feature を加えると KeyError が起こる原因調査

train のための forward の際には .user, .item, .inter の features が入力される。
しかし valid のための foward の際には .user の features のみが入力される。
このため、今回のケースで推論時に入力したいはずの .inter 内の features が入力されないということが起こっている。

[こちら](https://recbole.io/docs/user_guide/usage/running_new_dataset.html#convert-to-dataloader)によるとコンフィグファイルの eval_args を調整することで、そのあたりをコントロールできるかもしれない。

### TODO

- [x] eval_args の調整によって .inter の特徴量を .user と組み合わせて interaction を作成できないか調べる。

### 解決策

eval_args を以下のように変更することで解決した。

```diff
- mode: full
+ mode: uni001
```

eval_args 全コンフィグは以下である。

```yaml
eval_args:
    group_by: user  # user 単位でアイテムを集約して評価に使う。基本的にこれ以外使うことはない
    order: TO  # Temporal Order。時系列順で train, valid, test を分けてくれる
    split: {'RS': [0.8,0.1,0.1]}  # 80%, 10%, 10% で分けてくれる
    mode: uni001  # 1つのポジティブサンプルにつき、いくつのネガティブサンプルをどんな分布から何回行うか. uni001 は一様分布から1回行うの意. pop001 なども使える.
```
